version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth
    restart: unless-stopped

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python bot/bot.py
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./bot:/code/bot
      - ./config:/code/config
    restart: unless-stopped

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - ${MONGO_EXPRESS_HOST:-127.0.0.1}:${MONGO_EXPRESS_PORT:-8081}:8081
    depends_on:
      - mongo
    restart: unless-stopped
    env_file:
      - .env